//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class applications
    {
        public int id { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> type { get; set; }
        public string text { get; set; }
    
        public virtual application_types application_types { get; set; }
        public virtual users users { get; set; }
    }
}
