//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupons
    {
        public int id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string rule { get; set; }
        public Nullable<int> owner { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual coupon_statuses coupon_statuses { get; set; }
        public virtual menu menu { get; set; }
        public virtual orders orders { get; set; }
        public virtual users users { get; set; }
    }
}
