//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_dishes
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> dish_id { get; set; }
    
        public virtual dishes dishes { get; set; }
        public virtual orders orders { get; set; }
    }
}
